services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin-server
    ports:
      - "9411:9411"
    networks:
      - microservices-network
  naming-server:
    image: nicolasbuenno/naming-server:0.0.1-SNAPSHOT
    container_name: naming-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  api-gateway:
    image: nicolasbuenno/api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    restart: always
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
    networks:
      - microservices-network
  cambio-service:
    image: nicolasbuenno/cambio-service
    container_name: cambio-service
    restart: always
    build:
      context: .
      dockerfile: 02-cambio-service/cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&enableTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&enableTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123

    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - microservices-network

  book-service:
    image: nicolasbuenno/book-service
    container_name: book-service
    restart: always
    build:
      context: .
      dockerfile: 02-book-service/book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3311/book_service?useSSL=false&serverTimezone=UTC&enableTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3311/book_service?useSSL=false&serverTimezone=UTC&enableTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123

    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - book-db
    networks:
      - microservices-network
  
  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: cambio-db
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - microservices-network

  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: book-db
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3311
    ports:
      - "3311:3311"
    expose:
      - 3311
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
